# Generated by Django 2.1.5 on 2019-01-15 16:57

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cita', models.DateField(db_index=True)),
                ('hora_cita', models.TimeField(default=datetime.time(10, 10), verbose_name='Hora Facturacion')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario_cita', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
